self_healing:
  backup_retention_days: 7
  chrome_session_timeout: 30
  enabled: true
  failure_detection:
    confidence_threshold: 0.7
    enable_fingerprinting: true
  healing_timeout: 300
  locator_generation:
    max_alternatives: 5
    strategies:
    - id
    - name
    - css
    - xpath
    - link_text
  max_attempts_per_locator: 5
  max_concurrent_sessions: 3
  validation:
    element_wait_timeout: 10
    interaction_test: true
