"""
Framework audit floor — one audit_log row per authenticated state-changing
HTTP request, written automatically by a middleware floor (see main.py).

This module owns:
- resolve_actor_email: the SINGLE home of the 'unknown' fallback rule.
- actor_from_bearer:  attribution-only token decode (no DB, never raises).
- audit_log schema + init_audit_log(): created on the shared auth/users pool
  (auth.db.get_pool) — the same database as test_runs and users.
- write_audit_log:    the synchronous INSERT (run via asyncio.to_thread).
- record_request:     the async floor logic the middleware awaits.

Audit identity comes from the verified token ONLY, never client input.
'unknown' = an unidentified human (auth disabled / token-less local dev);
'system'  = a machine actor (service-to-service call, e.g. browser-service).

Referenced by: main.py (request_id_middleware floor + startup init).
Depends on: auth/db.py (shared pool), auth/jwt_utils.py (decode_token).
"""

import asyncio
import json
import logging
import re

from src.backend.auth.db import get_pool
from src.backend.auth.jwt_utils import decode_token

logger = logging.getLogger(__name__)

MUTATING_METHODS = frozenset({"POST", "PUT", "PATCH", "DELETE"})

# request.url.path is percent-decoded, so a crafted URL can smuggle CR/LF (log
# forging) or ANSI escapes (terminal injection) into it. Escape control chars
# before logging — mirrors the X-Request-ID sanitising in main.py.
_LOG_UNSAFE_RE = re.compile(r"[\x00-\x1f\x7f]")


def _safe_for_log(value: str) -> str:
    return _LOG_UNSAFE_RE.sub(lambda m: f"\\x{ord(m.group(0)):02x}", value)

# Known service-to-service (machine) endpoints that arrive without a user token.
# Single source of truth shared with the route-coverage CI test's machine
# allow-list. A token-less request to one of these is attributed to 'system'
# with the source recorded here (see record_request).
MACHINE_SOURCES: dict[str, str] = {
    "/api/workflow-metrics/record": "browser-service",
}


def resolve_actor_email(user: dict | None) -> str:
    """Audit identity from the verified token only, never client input.
    'unknown' = an unidentified human (auth disabled / token-less local dev),
    deliberately not a machine actor like 'system'. This is the ONLY place the
    'unknown' fallback rule lives."""
    return (user or {}).get("email") or "unknown"


def actor_from_bearer(authorization: str | None) -> dict | None:
    """Decode a bearer token for ATTRIBUTION ONLY — no DB, never raises.

    Returns the token's claims dict (email/user_id/org_id/...), or None if the
    header is absent, not a Bearer credential, or the token is malformed/expired.
    Authorization is unchanged and stays with each route's require_user/
    require_admin; this reads identity purely to attribute the audit row."""
    if not authorization:
        return None
    scheme, _, token = authorization.partition(" ")
    if scheme.lower() != "bearer" or not token:
        return None
    try:
        return decode_token(token)
    except Exception:  # noqa: BLE001 — a bad token must never break the floor
        return None


_AUDIT_LOG_DDL = (
    """
    CREATE TABLE IF NOT EXISTS audit_log (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
        actor_email   TEXT NOT NULL,
        actor_user_id TEXT,
        org_id        TEXT,
        method        TEXT NOT NULL,
        path          TEXT NOT NULL,
        status_code   INTEGER NOT NULL,
        source        TEXT NOT NULL DEFAULT 'backend',
        request_id    TEXT,
        detail        TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_audit_log_occurred ON audit_log(occurred_at)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_actor    ON audit_log(actor_email)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_org      ON audit_log(org_id)",
)


def init_audit_log() -> None:
    """Create the audit_log table + indexes if absent. Idempotent; run at
    startup (main.py). Uses the shared auth/users pool — the same database as
    test_runs and users."""
    with get_pool().connection() as conn:
        for ddl in _AUDIT_LOG_DDL:
            conn.execute(ddl)
        conn.commit()
    logger.info("[AUDIT] audit_log table ready")


def write_audit_log(
    *,
    actor_email: str,
    actor_user_id: str | None,
    org_id: str | None,
    method: str,
    path: str,
    status_code: int,
    request_id: str | None,
    source: str = "backend",
    detail: str | None = None,
) -> None:
    """Insert one audit_log row via the shared pool. Synchronous — call only
    from a worker thread (asyncio.to_thread). Raises on DB error; record_request
    wraps this so the floor fails open."""
    with get_pool().connection() as conn:
        conn.execute(
            "INSERT INTO audit_log "
            "(actor_email, actor_user_id, org_id, method, path, status_code, "
            "source, request_id, detail) "
            "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)",
            (actor_email, actor_user_id, org_id, method, path, status_code,
             source, request_id, detail),
        )
        conn.commit()


async def record_request(request, response, request_id: str | None) -> None:
    """Audit floor: for a mutating request, write ONE audit_log row attributing
    it to the verified token's email (or 'unknown'/'system'). Offloads the
    blocking INSERT to a worker thread so it never blocks the event loop. Fails
    open: any error is logged at error level and never raises, so the floor can
    never break a user action. Never reads the request body."""
    if request.method not in MUTATING_METHODS:
        return
    try:
        path = request.url.path
        user = actor_from_bearer(request.headers.get("Authorization"))
        if user is None and path in MACHINE_SOURCES:
            # Service-to-service call with no user token (e.g. browser-service).
            actor_email = "system"
            actor_user_id = None
            org_id = None
            source = MACHINE_SOURCES[path]
        else:
            # resolve_actor_email owns the 'unknown' fallback.
            actor_email = resolve_actor_email(user)
            actor_user_id = (user or {}).get("user_id")
            org_id = (user or {}).get("org_id")
            source = "backend"

        detail = getattr(request.state, "audit_detail", None)
        detail_json = json.dumps(detail) if detail is not None else None

        await asyncio.to_thread(
            write_audit_log,
            actor_email=actor_email,
            actor_user_id=actor_user_id,
            org_id=org_id,
            method=request.method,
            path=path,
            status_code=response.status_code,
            request_id=request_id,
            source=source,
            detail=detail_json,
        )
    except Exception:  # noqa: BLE001 — the floor must never break a user action
        logger.error(
            "[AUDIT] floor write failed: %s %s",
            _safe_for_log(request.method), _safe_for_log(request.url.path),
            exc_info=True,
        )
