"""
Workflow metrics storage and retrieval for browser-use workflows.
Tracks metrics for cost optimization and monitoring.

This module provides:
- WorkflowMetrics: The main model (imported from core.models)
- WorkflowMetricsCollector: Storage and retrieval of metrics
- Utility functions: count_tokens, calculate_crewai_cost
"""

import json
import logging
from datetime import datetime
from typing import Dict, List, Optional, Any
from threading import Lock

import psycopg
from psycopg_pool import ConnectionPool

from src.backend.core.config import settings
# Import the Pydantic model from models
from .models import WorkflowMetrics

logger = logging.getLogger(__name__)

_SCHEMA_DDL = (
    """
    CREATE TABLE IF NOT EXISTS workflow_metrics (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id TEXT,
        ts          TIMESTAMP NOT NULL,
        data        JSONB NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_workflow_metrics_ts ON workflow_metrics (ts DESC)",
)


class WorkflowMetricsCollector:
    """
    Collects and stores workflow metrics in Postgres for monitoring and analysis.

    Phase 4 consolidation: replaces the former logs/workflow_metrics.jsonl file.
    Each run is one row — the full WorkflowMetrics.to_dict() kept as jsonb
    (lossless), plus an extracted ts + workflow_id so ORDER BY / date-range
    filtering happen natively in SQL. `ts` is a naive TIMESTAMP (not timestamptz)
    because the source timestamps are naive datetime.now() values; storing them
    tz-naive preserves the original range-filter semantics exactly.
    """

    def __init__(self, dsn: str = None):
        self.dsn = dsn or settings.DATABASE_URL
        setup = psycopg.connect(self.dsn, autocommit=True)
        try:
            for ddl in _SCHEMA_DDL:
                setup.execute(ddl)
        finally:
            setup.close()
        self._pool = ConnectionPool(conninfo=self.dsn, min_size=1, max_size=4, open=True)
        logger.info("[WORKFLOW_METRICS] Postgres workflow-metrics store ready")

    def close(self) -> None:
        """Close the connection pool (tests; the app singleton lives for the process)."""
        self._pool.close()

    def _rows_to_metrics(self, rows) -> List[WorkflowMetrics]:
        out: List[WorkflowMetrics] = []
        for (data,) in rows:
            try:
                out.append(WorkflowMetrics.from_dict(data))
            except Exception as e:
                logger.warning(f"Skipping invalid metrics row: {e}")
        return out

    def record_workflow(self, metrics: WorkflowMetrics) -> None:
        """Record a workflow execution's metrics (one jsonb row)."""
        try:
            payload = json.dumps(metrics.to_dict())
            with self._pool.connection() as conn:
                conn.execute(
                    "INSERT INTO workflow_metrics (workflow_id, ts, data) "
                    "VALUES (%s, %s, %s::jsonb)",
                    (metrics.workflow_id, metrics.timestamp, payload),
                )
            logger.info(f"Recorded metrics for workflow {metrics.workflow_id}")
        except Exception as e:
            logger.error(f"Failed to record workflow metrics: {e}")

    def get_all_metrics(self, limit: Optional[int] = None) -> List[WorkflowMetrics]:
        """Get all recorded metrics, most-recent first, optionally limited to N."""
        sql = "SELECT data FROM workflow_metrics ORDER BY ts DESC"
        params: tuple = ()
        if limit:
            sql += " LIMIT %s"
            params = (limit,)
        try:
            with self._pool.connection() as conn:
                rows = conn.execute(sql, params).fetchall()
            return self._rows_to_metrics(rows)
        except Exception as e:
            logger.error(f"Failed to read workflow metrics: {e}")
            return []

    def get_metrics_by_date_range(
        self,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None
    ) -> List[WorkflowMetrics]:
        """Get metrics within a date range (native SQL filter), most-recent first."""
        clauses: List[str] = []
        params: List[Any] = []
        if start_date:
            clauses.append("ts >= %s")
            params.append(start_date)
        if end_date:
            clauses.append("ts <= %s")
            params.append(end_date)
        where = (" WHERE " + " AND ".join(clauses)) if clauses else ""
        sql = f"SELECT data FROM workflow_metrics{where} ORDER BY ts DESC"
        try:
            with self._pool.connection() as conn:
                rows = conn.execute(sql, tuple(params)).fetchall()
            return self._rows_to_metrics(rows)
        except Exception as e:
            logger.error(f"Failed to read workflow metrics: {e}")
            return []
    
    def get_aggregate_metrics(
        self,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None
    ) -> Dict[str, Any]:
        """Get aggregated metrics for a date range."""
        metrics = self.get_metrics_by_date_range(start_date, end_date)
        
        if not metrics:
            return {
                'total_workflows': 0,
                'total_elements': 0,
                'successful_elements': 0,
                'failed_elements': 0,
                'avg_success_rate': 0.0,
                'total_llm_calls': 0,
                'avg_llm_calls_per_element': 0.0,
                'total_cost': 0.0,
                'avg_cost_per_element': 0.0,
                'custom_action_usage_rate': 0.0,
                'avg_execution_time': 0.0,
                'date_range': {
                    'start': start_date.isoformat() if start_date else None,
                    'end': end_date.isoformat() if end_date else None
                }
            }
        
        total_workflows = len(metrics)
        total_elements = sum(m.total_elements for m in metrics)
        successful_elements = sum(m.successful_elements for m in metrics)
        failed_elements = sum(m.failed_elements for m in metrics)
        total_llm_calls = sum(m.total_llm_calls for m in metrics)
        total_cost = sum(m.total_cost for m in metrics)
        custom_action_workflows = sum(1 for m in metrics if m.custom_actions_enabled)
        total_execution_time = sum(m.execution_time for m in metrics)
        
        return {
            'total_workflows': total_workflows,
            'total_elements': total_elements,
            'successful_elements': successful_elements,
            'failed_elements': failed_elements,
            'avg_success_rate': (successful_elements / total_elements * 100) if total_elements > 0 else 0.0,
            'total_llm_calls': total_llm_calls,
            'avg_llm_calls_per_element': total_llm_calls / total_elements if total_elements > 0 else 0.0,
            'total_cost': total_cost,
            'avg_cost_per_element': total_cost / total_elements if total_elements > 0 else 0.0,
            'custom_action_usage_rate': (custom_action_workflows / total_workflows * 100) if total_workflows > 0 else 0.0,
            'avg_execution_time': total_execution_time / total_workflows if total_workflows > 0 else 0.0,
            'date_range': {
                'start': start_date.isoformat() if start_date else None,
                'end': end_date.isoformat() if end_date else None
            }
        }


# Global instance
_metrics_collector: Optional[WorkflowMetricsCollector] = None
# Guards singleton initialisation so two concurrent first-callers cannot create
# two separate instances each with their own self._lock, which would allow
# concurrent file writes from different lock objects to the same JSONL file.
_metrics_collector_init_lock = Lock()


def get_workflow_metrics_collector() -> WorkflowMetricsCollector:
    """Get the global workflow metrics collector instance (thread-safe)."""
    global _metrics_collector
    if _metrics_collector is None:
        with _metrics_collector_init_lock:
            if _metrics_collector is None:  # double-checked locking
                _metrics_collector = WorkflowMetricsCollector()
    return _metrics_collector


def count_tokens(text: str, model: str | None = None) -> int:
    """
    Count tokens in text using LiteLLM's accurate token counter.

    LiteLLM provides accurate token counting for the specific model being used,
    which is more reliable than word-based estimation for cost tracking.

    Args:
        text: Text to count tokens for
        model: LiteLLM model string (e.g. "gemini/gemini-2.5-flash"). Defaults
               to the currently configured ONLINE_MODEL when not specified.

    Returns:
        Accurate token count for the specified model

    Example:
        >>> count_tokens("Hello world, this is a test")
        7  # Accurate count vs estimated 8
    """
    if not text:
        return 0

    if model is None:
        from src.backend.crew_ai.llm_provider_routing import resolve_model_string
        from src.backend.core.config import settings
        model = resolve_model_string(settings.MODEL_PROVIDER, settings.ONLINE_MODEL)

    try:
        from litellm import token_counter
        return token_counter(model=model, text=text)
    except Exception as e:
        # Fallback to word-based estimation if LiteLLM fails
        logger.warning(f"LiteLLM token counting failed, using estimation: {e}")
        words = text.split()
        return int(len(words) * 1.33)


def calculate_crewai_cost(usage_metrics: dict, model_name: str | None = None) -> dict:
    """
    Extract cost and token metrics from CrewAI's usage_metrics.
    
    CrewAI already calculates cost via LiteLLM internally, so we simply extract it.
    No need to recalculate what's already been calculated!
    
    Args:
        usage_metrics: Usage metrics dict from CrewAI with keys:
            - total_tokens: Total tokens used
            - prompt_tokens: Input tokens
            - completion_tokens: Output tokens
            - successful_requests: Number of successful LLM calls
            - total_cost: Cost already calculated by CrewAI/LiteLLM
        model_name: Model name (for logging/fallback only)
    
    Returns:
        Dict with llm_calls, cost, tokens breakdown
    
    Example:
        >>> crew = Crew(agents=[...], tasks=[...])
        >>> result = crew.kickoff()
        >>> usage_obj = crew.calculate_usage_metrics()  # CrewAI 1.3.0+
        >>> usage_dict = {
        ...     'total_tokens': usage_obj.total_tokens,
        ...     'prompt_tokens': usage_obj.prompt_tokens,
        ...     'completion_tokens': usage_obj.completion_tokens,
        ...     'successful_requests': usage_obj.successful_requests,
        ...     'total_cost': usage_obj.total_cost  # Already calculated!
        ... }
        >>> metrics = calculate_crewai_cost(usage_dict, "gemini-2.5-flash")
        >>> print(f"Cost: ${metrics['cost']:.4f}")
    
    Note:
        If total_cost is not available (old CrewAI versions), falls back to LiteLLM calculation.
    """
    if model_name is None:
        from src.backend.crew_ai.llm_provider_routing import resolve_model_string
        from src.backend.core.config import settings
        model_name = resolve_model_string(settings.MODEL_PROVIDER, settings.ONLINE_MODEL)

    prompt_tokens = usage_metrics.get('prompt_tokens', 0)
    completion_tokens = usage_metrics.get('completion_tokens', 0)
    total_tokens = usage_metrics.get('total_tokens', 0)

    # First, try to use the cost already calculated by CrewAI
    cost = usage_metrics.get('total_cost', None)
    
    if cost is not None:
        logger.info(f"💰 CrewAI cost extracted directly: ${cost:.6f} (model: {model_name})")
    else:
        # Calculate via LiteLLM's completion_cost() function
        # LiteLLM caches pricing data internally and is always available when Gemini API is
        logger.info(f"💰 Calculating CrewAI cost via LiteLLM for model: {model_name}")
        
        from litellm import completion_cost
        
        # completion_cost() expects a completion response object
        # Create a minimal response object with the token usage
        completion_response = {
            "model": model_name,
            "usage": {
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": total_tokens
            }
        }
        
        cost = completion_cost(completion_response=completion_response)
        logger.info(f"💰 CrewAI cost calculated: ${cost:.6f} (model: {model_name})")
    
    return {
        'llm_calls': usage_metrics.get('successful_requests', 0),
        'cost': round(cost, 6),
        'tokens': total_tokens,
        'prompt_tokens': prompt_tokens,
        'completion_tokens': completion_tokens
    }


# Re-export WorkflowMetrics for backward compatibility
__all__ = [
    'WorkflowMetrics',
    'WorkflowMetricsCollector',
    'get_workflow_metrics_collector',
    'count_tokens',
    'calculate_crewai_cost',
]
