"""
PostgreSQL schema for the learning store (Phase 4 migration).

This is the consolidated, final-state DDL — the Postgres equivalent of all 14
SQLite migrations in schema_manager.py, collapsed into one CREATE-IF-NOT-EXISTS
schema (a fresh Postgres DB has no history to replay). Future schema changes add
numbered entries to PG_MIGRATIONS and bump SCHEMA_VERSION.

Porting decisions (minimise code churn — mirror SQLite shapes, not "ideal" PG):
- INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
- Timestamps stay TEXT (ISO-8601 strings), exactly like SQLite, so the engines'
  read/write code is unchanged. (Not native timestamptz — deliberate.)
- Boolean-ish columns stay INTEGER (is_active, test_passed, …) so engine code
  like `WHERE is_active = 1` ports verbatim.
- REAL -> DOUBLE PRECISION. JSON arrays stay TEXT (the dashboard JSON queries
  are ported separately to jsonb functions at read time).

Referenced by: postgres_execution_memory.py (Phase 4).
"""

import logging

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 22

# The version of the consolidated baseline (PG_SCHEMA_DDL). It is recorded once
# so that every migration newer than the baseline is applied on top — including
# on an EXISTING database. It must NOT track SCHEMA_VERSION: stamping the latest
# version here would pre-record pending migrations and cause them to be skipped,
# leaving an existing database un-upgraded. Bump this only when migrations are
# folded back into the baseline DDL (a re-consolidation), not when adding one.
_BASELINE_VERSION = 16

# Each statement is executed once inside ensure_schema(). Ordered so referenced
# tables (nl_feedback_corrections, hint_review_sessions) exist before FKs.
# NOTE: org_id columns appear in the CREATE TABLE bodies for fresh installs, but
# their indexes (and the ADD COLUMN for already-existing tables) live ONLY in the
# v17 migration below — a baseline `CREATE INDEX ... (org_id)` would fail on a
# pre-1c table whose org_id column the migration has not added yet.
PG_SCHEMA_DDL: tuple[str, ...] = (
    # --- schema_version bookkeeping ---
    """
    CREATE TABLE IF NOT EXISTS schema_version (
        version     INTEGER PRIMARY KEY,
        description TEXT,
        applied_at  TEXT NOT NULL
    )
    """,

    # --- execution_records (cols consolidated through v13) ---
    """
    CREATE TABLE IF NOT EXISTS execution_records (
        id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id           TEXT UNIQUE NOT NULL,
        timestamp             TEXT NOT NULL,
        user_query            TEXT NOT NULL,
        url                   TEXT,
        domain                TEXT,
        robot_code            TEXT,
        code_structure        TEXT,
        test_status           TEXT NOT NULL,
        execution_exit_code   INTEGER,
        execution_duration_ms INTEGER,
        failure_category      TEXT,
        failed_keyword        TEXT,
        error_message         TEXT,
        total_llm_calls       INTEGER DEFAULT 0,
        total_cost            DOUBLE PRECISION DEFAULT 0.0,
        user_feedback         TEXT,
        user_feedback_type    TEXT,
        working_code          TEXT,
        injected_hint_ids     JSONB,
        model_version         TEXT,
        hint_attribution_done INTEGER NOT NULL DEFAULT 1,
        org_id TEXT,
        CONSTRAINT chk_status CHECK (test_status IN ('passed', 'failed', 'error'))
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_exec_domain ON execution_records(domain)",
    "CREATE INDEX IF NOT EXISTS idx_exec_status ON execution_records(test_status)",
    "CREATE INDEX IF NOT EXISTS idx_exec_failure ON execution_records(failure_category)",
    "CREATE INDEX IF NOT EXISTS idx_exec_timestamp ON execution_records(timestamp)",
    "CREATE INDEX IF NOT EXISTS idx_exec_structure ON execution_records(code_structure)",
    # GIN index for jsonb hint-id membership (injected_hint_ids @> to_jsonb(id)) — Tier 1.
    "CREATE INDEX IF NOT EXISTS idx_exec_injected_gin ON execution_records USING GIN (injected_hint_ids)",

    # --- intent_patterns ---
    """
    CREATE TABLE IF NOT EXISTS intent_patterns (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        intent_name      TEXT UNIQUE NOT NULL,
        triggers_json    TEXT NOT NULL,
        requires_json    TEXT NOT NULL,
        source           TEXT NOT NULL,
        score            DOUBLE PRECISION DEFAULT 0.5,
        evidence_count   INTEGER DEFAULT 0,
        counter_evidence INTEGER DEFAULT 0,
        last_triggered   TEXT,
        last_updated     TEXT NOT NULL,
        created_at       TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_intent_score ON intent_patterns(score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intent_source ON intent_patterns(source)",

    # --- structural_rules ---
    """
    CREATE TABLE IF NOT EXISTS structural_rules (
        id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        rule_name              TEXT UNIQUE NOT NULL,
        query_pattern          TEXT NOT NULL,
        required_structure     TEXT NOT NULL,
        required_keywords_json TEXT,
        code_template          TEXT,
        score                  DOUBLE PRECISION DEFAULT 0.5,
        evidence_count         INTEGER DEFAULT 0,
        counter_evidence       INTEGER DEFAULT 0,
        last_triggered         TEXT,
        last_updated           TEXT NOT NULL,
        created_at             TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_rules_score ON structural_rules(score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_rules_score_evidence ON structural_rules(score DESC, evidence_count DESC)",

    # --- keyword_corrections ---
    """
    CREATE TABLE IF NOT EXISTS keyword_corrections (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        wrong_keyword   TEXT NOT NULL,
        correct_keyword TEXT,
        library         TEXT DEFAULT 'browser',
        error_pattern   TEXT,
        score           DOUBLE PRECISION DEFAULT 0.5,
        evidence_count  INTEGER DEFAULT 1,
        last_seen       TEXT NOT NULL,
        UNIQUE(wrong_keyword, library)
    )
    """,

    # --- anti_patterns ---
    """
    CREATE TABLE IF NOT EXISTS anti_patterns (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        failure_category    TEXT NOT NULL,
        query_pattern       TEXT,
        bad_code_snippet    TEXT,
        error_message       TEXT,
        correct_alternative TEXT,
        domain              TEXT,
        score               DOUBLE PRECISION DEFAULT 0.5,
        evidence_count      INTEGER DEFAULT 1,
        last_seen           TEXT NOT NULL,
        org_id              TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_anti_category ON anti_patterns(failure_category)",
    "CREATE INDEX IF NOT EXISTS idx_anti_domain ON anti_patterns(domain)",
    "CREATE INDEX IF NOT EXISTS idx_anti_score_evidence ON anti_patterns(score DESC, evidence_count DESC)",

    # --- learning_stats ---
    """
    CREATE TABLE IF NOT EXISTS learning_stats (
        id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stat_date            TEXT NOT NULL,
        total_executions     INTEGER DEFAULT 0,
        total_passed         INTEGER DEFAULT 0,
        total_failed         INTEGER DEFAULT 0,
        rules_applied        INTEGER DEFAULT 0,
        rules_effective      INTEGER DEFAULT 0,
        avg_cost             DOUBLE PRECISION,
        avg_delegation_count DOUBLE PRECISION,
        feedback_received    INTEGER DEFAULT 0,
        UNIQUE(stat_date)
    )
    """,

    # --- learning_metrics (+ was_holdout v11) ---
    """
    CREATE TABLE IF NOT EXISTS learning_metrics (
        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id             TEXT NOT NULL,
        user_query              TEXT NOT NULL,
        is_first_attempt        INTEGER NOT NULL DEFAULT 1,
        is_retry_after_feedback INTEGER NOT NULL DEFAULT 0,
        attempt_number          INTEGER NOT NULL DEFAULT 1,
        hints_available         INTEGER NOT NULL DEFAULT 0,
        hints_injected          INTEGER NOT NULL DEFAULT 0,
        hint_sources            JSONB DEFAULT '[]'::jsonb,
        llm_calls               INTEGER NOT NULL DEFAULT 0,
        llm_cost                DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        hint_tokens             INTEGER NOT NULL DEFAULT 0,
        test_passed             INTEGER NOT NULL,
        timestamp               TEXT NOT NULL,
        was_holdout             INTEGER NOT NULL DEFAULT 0
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_metrics_workflow ON learning_metrics(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_metrics_first_attempt ON learning_metrics(is_first_attempt)",
    "CREATE INDEX IF NOT EXISTS idx_metrics_hints ON learning_metrics(hints_injected)",

    # --- nl_feedback_corrections (cols consolidated through v13) ---
    """
    CREATE TABLE IF NOT EXISTS nl_feedback_corrections (
        id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        feedback_text             TEXT NOT NULL,
        category                  TEXT NOT NULL DEFAULT 'uncategorized',
        scope                     TEXT NOT NULL DEFAULT 'domain',
        domain                    TEXT,
        url                       TEXT,
        original_failure_category TEXT,
        evidence_count            INTEGER NOT NULL DEFAULT 1,
        applied_count             INTEGER NOT NULL DEFAULT 0,
        success_count             INTEGER NOT NULL DEFAULT 0,
        failure_count             INTEGER NOT NULL DEFAULT 0,
        is_active                 INTEGER NOT NULL DEFAULT 1,
        source_workflow_id        TEXT,
        created_at                TEXT NOT NULL,
        last_seen                 TEXT NOT NULL,
        conflict_flagged          INTEGER NOT NULL DEFAULT 0,
        conflict_flagged_at       TEXT,
        conflict_flag_reason      TEXT,
        created_via               TEXT NOT NULL DEFAULT 'workflow',
        disabled_at               TEXT,
        anchor_query              TEXT,
        unused_count              INTEGER NOT NULL DEFAULT 0,
        org_id                    TEXT
    )
    """,
    # Dedup uniqueness lives in the v18 migration (org-aware, mirrors the
    # engine's dedup keys), NOT here — a baseline unique index on org_id would
    # fail on a pre-1c table whose org_id column the v17 migration has not
    # added yet (same reasoning as the v17 org indexes).
    "CREATE INDEX IF NOT EXISTS idx_nlfc_domain ON nl_feedback_corrections(domain)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_scope ON nl_feedback_corrections(scope)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_active ON nl_feedback_corrections(is_active)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_domain_scope ON nl_feedback_corrections(domain, scope)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_conflict ON nl_feedback_corrections(conflict_flagged)",
    # Partial index for the hot hint-retrieval filter (active, unflagged) — Tier 1.
    "CREATE INDEX IF NOT EXISTS idx_nlfc_active_unflagged ON nl_feedback_corrections(scope, domain) "
    "WHERE is_active = 1 AND conflict_flagged = 0",

    # --- trigger_events (cols consolidated through v13) ---
    """
    CREATE TABLE IF NOT EXISTS trigger_events (
        id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trigger_type              TEXT NOT NULL,
        workflow_id               TEXT,
        domain                    TEXT,
        url                       TEXT,
        feedback_text             TEXT,
        active_hint_ids           JSONB,
        flagged_hint_ids          JSONB,
        reason                    TEXT,
        llm_model                 TEXT,
        input_tokens              INTEGER,
        output_tokens             INTEGER,
        llm_latency_ms            INTEGER,
        status                    TEXT NOT NULL,
        error_message             TEXT,
        created_at                TEXT NOT NULL,
        actually_flagged_hint_ids JSONB,
        used_hint_ids             JSONB,
        unused_hint_ids           JSONB
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_trigger_events_created ON trigger_events(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_events_workflow ON trigger_events(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_events_type ON trigger_events(trigger_type)",
    # GIN indexes for jsonb hint-id membership (col @> to_jsonb(id)) — Tier 1.
    "CREATE INDEX IF NOT EXISTS idx_trigger_active_gin ON trigger_events USING GIN (active_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_flagged_gin ON trigger_events USING GIN (flagged_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_actually_flagged_gin ON trigger_events USING GIN (actually_flagged_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_used_gin ON trigger_events USING GIN (used_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_unused_gin ON trigger_events USING GIN (unused_hint_ids)",

    # --- hint_audit (FK -> nl_feedback_corrections) ---
    """
    CREATE TABLE IF NOT EXISTS hint_audit (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hint_id      INTEGER NOT NULL,
        action       TEXT NOT NULL,
        actor        TEXT NOT NULL,
        reason       TEXT,
        before_value TEXT,
        after_value  TEXT,
        created_at   TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_hint_audit_hint ON hint_audit(hint_id)",
    "CREATE INDEX IF NOT EXISTS idx_hint_audit_created ON hint_audit(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_hint_audit_actor ON hint_audit(actor)",

    # --- hint_evidence (independent-source counts; no FK by design) ---
    # The four event counters on nl_feedback_corrections count OUTCOMES, so one
    # query re-run five times is indistinguishable from five different queries
    # agreeing. This table records the distinct SOURCE behind each outcome, so
    # the shield / auto-disable / auto-retire rules can require diversity while
    # the event counters keep their meaning (they feed LLM prompts and KPIs).
    #
    # source_hash (sha256 hex of source_key) is the indexed key, not the text:
    # `Query.query` is uncapped end to end, and a fixed 64-char key stays within
    # the 2704-byte btree limit and stays correct on multiple replicas.
    # source_key is kept unindexed so a row is still readable when debugging.
    #
    # uq_hint_evidence leads with hint_id and serves every hint_id-leading
    # lookup (_source_counts, T5's ON CONFLICT probe, T12's hint_id IN (...))
    # index-only for the hot COUNT(DISTINCT). It does NOT serve
    # get_corrections_for_run (nl_feedback_engine.py), which filters on
    # source_kind/bucket/source_hash with no hint_id and was seq-scanning on
    # every FeedbackPanel mount — idx_hint_evidence_source (v22, below) covers
    # that lookup instead. No CHECK on source_kind/bucket either: a CHECK
    # firing would roll the ENTIRE attribution transaction back on every run
    # until a code fix, which is a larger silent failure than the junk rows
    # it would prevent.
    """
    CREATE TABLE IF NOT EXISTS hint_evidence (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hint_id     INTEGER NOT NULL,
        source_kind TEXT    NOT NULL,   -- 'query' | 'workflow'
        source_key  TEXT    NOT NULL,   -- normalised user_query | workflow_id
        source_hash TEXT    NOT NULL,   -- sha256 hex of source_key
        bucket      TEXT    NOT NULL,   -- 'used' | 'failure' | 'unused' | 'evidence'
        created_at  TEXT    NOT NULL
    )
    """,
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_hint_evidence "
    "ON hint_evidence (hint_id, source_kind, source_hash, bucket)",

    # --- hint_review_sessions ---
    """
    CREATE TABLE IF NOT EXISTS hint_review_sessions (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status         TEXT NOT NULL DEFAULT 'pending_llm',
        hint_count     INTEGER NOT NULL DEFAULT 0,
        llm_model      TEXT,
        llm_latency_ms INTEGER,
        warning        TEXT,
        error_message  TEXT,
        created_at     TEXT NOT NULL,
        completed_at   TEXT
    )
    """,

    # --- hint_review_recommendations ---
    """
    CREATE TABLE IF NOT EXISTS hint_review_recommendations (
        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id        INTEGER NOT NULL,
        hint_id           INTEGER NOT NULL,
        recommendation    TEXT NOT NULL,
        reason            TEXT NOT NULL,
        exoneration_count INTEGER NOT NULL DEFAULT 0,
        admin_decision    TEXT,
        admin_notes       TEXT,
        decided_at        TEXT,
        applied           INTEGER NOT NULL DEFAULT 0,
        created_at        TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_hrr_session ON hint_review_recommendations(session_id)",
    "CREATE INDEX IF NOT EXISTS idx_hrr_hint ON hint_review_recommendations(hint_id)",

    # --- hint_review_pages ---
    """
    CREATE TABLE IF NOT EXISTS hint_review_pages (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id     INTEGER NOT NULL,
        scope_type     TEXT NOT NULL,
        scope_value    TEXT,
        status         TEXT NOT NULL,
        hint_count     INTEGER NOT NULL,
        llm_latency_ms INTEGER,
        error_message  TEXT,
        retry_count    INTEGER DEFAULT 0,
        created_at     TEXT NOT NULL,
        completed_at   TEXT,
        org_id         TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_review_pages_session ON hint_review_pages(session_id)",

    # --- hint_workflow_trace (composite PK, no FK by design) ---
    """
    CREATE TABLE IF NOT EXISTS hint_workflow_trace (
        workflow_id        TEXT NOT NULL,
        hint_id            INTEGER NOT NULL,
        scope              TEXT,
        source             TEXT,
        priority           TEXT,
        similarity_score   DOUBLE PRECISION,
        available          INTEGER NOT NULL DEFAULT 0,
        injected           INTEGER NOT NULL DEFAULT 0,
        drop_reason        TEXT,
        attribution_bucket TEXT,
        attribution_reason TEXT,
        created_at         TEXT NOT NULL,
        PRIMARY KEY (workflow_id, hint_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_hint_trace_created_at ON hint_workflow_trace(created_at)",

    # --- pgvector embeddings (Phase 4 slice 6; replaces ChromaDB) ---
    # SCHEMA public pins the extension so the vector TYPE resolves from any
    # search_path that includes public. Without it, the first bootstrap on a
    # fresh database (e.g. CI's service container) installs into the first
    # search_path schema — an isolated test schema — and every other schema's
    # DDL then fails with 'type "vector" does not exist'.
    # 384 dims = fastembed all-MiniLM-L6-v2 (see embedding.EMBED_MODEL).
    "CREATE EXTENSION IF NOT EXISTS vector SCHEMA public",
    # learning_anchors — the hint-retrieval similarity gate (filter_by_query_similarity).
    """
    CREATE TABLE IF NOT EXISTS learning_anchors (
        anchor_key   TEXT PRIMARY KEY,
        kind         TEXT NOT NULL,
        record_id    BIGINT NOT NULL,
        anchor_query TEXT NOT NULL,
        embedding    vector(384) NOT NULL,
        org_id       TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_anchors_kind_record ON learning_anchors(kind, record_id)",
    "CREATE INDEX IF NOT EXISTS idx_anchors_embedding "
    "ON learning_anchors USING hnsw (embedding vector_cosine_ops)",
    # execution_embeddings — per-execution query embeddings (find_similar_executions).
    """
    CREATE TABLE IF NOT EXISTS execution_embeddings (
        workflow_id      TEXT PRIMARY KEY,
        user_query       TEXT,
        test_status      TEXT,
        failure_category TEXT,
        domain           TEXT,
        code_structure   TEXT,
        embedding        vector(384) NOT NULL,
        org_id           TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_exec_emb_embedding "
    "ON execution_embeddings USING hnsw (embedding vector_cosine_ops)",

    # --- SQLite-compat SQL functions (so the engines' SQLite SQL runs as-is) ---
    # NOTE: json_each / json_valid were retired in slice 4.5 — the hint-id array
    # columns are now native jsonb and the KPI queries use jsonb operators
    # (col @> to_jsonb(id)) directly, so no text-JSON emulation is needed.
    # SQLite datetime('now', <modifiers...>) -> Postgres text "YYYY-MM-DD HH24:MI:SS".
    # The engines only use 'now'/'localtime' and day-interval modifiers
    # ("-30 days", "? || ' days'"); all base modifiers map to **UTC** and
    # interval modifiers are applied on top.
    # UTC, NOT localtimestamp: the Python writers in the same tables stamp
    # datetime.now(timezone.utc), and with run.sh the backend (host TZ) and
    # Postgres (UTC container) disagree on "local" — server-local here would
    # skew every cross-writer comparison and retention window by the TZ offset.
    # ('localtime' is accepted for source compatibility but still means UTC.)
    """
    CREATE OR REPLACE FUNCTION datetime(VARIADIC mods text[])
    RETURNS text LANGUAGE plpgsql AS $fn$
    DECLARE ts timestamp := (now() at time zone 'utc'); m text; i int;
    BEGIN
        IF mods IS NOT NULL THEN
            FOR i IN 1 .. COALESCE(array_length(mods, 1), 0) LOOP
                m := mods[i];
                IF m IS NULL OR m IN ('now', 'localtime', 'utc') THEN
                    CONTINUE;
                ELSIF m ~* '(day|hour|month|year|minute|second|week)' THEN
                    ts := ts + m::interval;
                END IF;
            END LOOP;
        END IF;
        RETURN to_char(ts, 'YYYY-MM-DD HH24:MI:SS');
    END $fn$
    """,
    # SQLite last_insert_rowid() -> Postgres lastval() (last IDENTITY/sequence
    # value in the session). Valid only right after an INSERT on the same conn,
    # which is exactly how the call sites use it.
    """
    CREATE OR REPLACE FUNCTION last_insert_rowid()
    RETURNS bigint LANGUAGE sql AS $fn$ SELECT lastval() $fn$
    """,
)


# ---------------------------------------------------------------------------
# Forward-only migrations for EXISTING databases.
#
# The consolidated DDL above always describes the CURRENT schema, but CREATE
# IF NOT EXISTS never alters a table that already exists — so a change to an
# existing table needs BOTH:
#   1. the change folded into PG_SCHEMA_DDL (fresh databases), AND
#   2. a numbered entry here (existing databases), AND
#   3. SCHEMA_VERSION bumped to the new number.
# Contract: every migration statement must be idempotent (ADD COLUMN IF NOT
# EXISTS, CREATE INDEX IF NOT EXISTS, …) — on a fresh database the baseline
# DDL already contains the change and the migration re-runs as a no-op.
# Each entry: (version, description, (statement, ...)).
# ---------------------------------------------------------------------------
PG_MIGRATIONS: tuple[tuple[int, str, tuple[str, ...]], ...] = (
    (17, "Phase 1c: org_id on scoped learning tables + is_shared on hints",
     (
         "ALTER TABLE execution_records ADD COLUMN IF NOT EXISTS org_id TEXT",
         "ALTER TABLE nl_feedback_corrections ADD COLUMN IF NOT EXISTS org_id TEXT",
         "ALTER TABLE nl_feedback_corrections ADD COLUMN IF NOT EXISTS is_shared INTEGER NOT NULL DEFAULT 0",
         "ALTER TABLE anti_patterns ADD COLUMN IF NOT EXISTS org_id TEXT",
         "ALTER TABLE learning_anchors ADD COLUMN IF NOT EXISTS org_id TEXT",
         "ALTER TABLE execution_embeddings ADD COLUMN IF NOT EXISTS org_id TEXT",
         "CREATE INDEX IF NOT EXISTS idx_exec_org ON execution_records(org_id)",
         "CREATE INDEX IF NOT EXISTS idx_nlfc_org_shared ON nl_feedback_corrections(org_id, is_shared)",
         "CREATE INDEX IF NOT EXISTS idx_anti_org ON anti_patterns(org_id)",
         "CREATE INDEX IF NOT EXISTS idx_anchors_org ON learning_anchors(org_id)",
         "CREATE INDEX IF NOT EXISTS idx_exec_emb_org ON execution_embeddings(org_id)",
     )),
    (18, "Org-aware hint dedup uniqueness (replaces org-blind UNIQUE constraint)",
     (
         # The inline UNIQUE(feedback_text, domain, scope) was org-blind: a
         # second org's identical feedback could never get its own row (the
         # engine's org-scoped dedup finds no match, then the INSERT dies on
         # the constraint and the hint is silently dropped). Replace it with
         # unique indexes that mirror the engine's actual dedup keys:
         #   non-url scopes: (text, domain, scope, org)
         #   url scope:      (text, domain, url, scope, org)  — the url column
         #     is part of the engine's dedup key for url-scoped hints, which
         #     the old constraint contradicted (second page's identical hint
         #     was silently dropped).
         # COALESCE(org_id,'') keeps legacy/global NULL-org rows deduping
         # among themselves (btree NULLs are otherwise always distinct).
         # domain/url stay plain columns: NULL-distinct matches the old
         # constraint's behaviour, so index creation cannot fail on legacy rows.
         "ALTER TABLE nl_feedback_corrections "
         "DROP CONSTRAINT IF EXISTS nl_feedback_corrections_feedback_text_domain_scope_key",
         "CREATE UNIQUE INDEX IF NOT EXISTS uq_nlfc_dedup_general "
         "ON nl_feedback_corrections (feedback_text, domain, scope, COALESCE(org_id, '')) "
         "WHERE scope <> 'url'",
         "CREATE UNIQUE INDEX IF NOT EXISTS uq_nlfc_dedup_url "
         "ON nl_feedback_corrections (feedback_text, domain, url, scope, COALESCE(org_id, '')) "
         "WHERE scope = 'url'",
     )),
    (19, "hint_evidence: independent-source counts behind each hint outcome",
     (
         "CREATE TABLE IF NOT EXISTS hint_evidence ("
         " id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
         " hint_id     INTEGER NOT NULL,"
         " source_kind TEXT    NOT NULL,"
         " source_key  TEXT    NOT NULL,"
         " source_hash TEXT    NOT NULL,"
         " bucket      TEXT    NOT NULL,"
         " created_at  TEXT    NOT NULL)",
         "CREATE UNIQUE INDEX IF NOT EXISTS uq_hint_evidence "
         "ON hint_evidence (hint_id, source_kind, source_hash, bucket)",
     )),
    (20, "Every hint is owned by exactly one org: drop is_shared",
     (
         # is_shared was read on retrieval only, never on mutation — the
         # counter, flag, disable and retire writes are all bare WHERE id = ?.
         # A hint visible to every org therefore had its lifecycle decided by
         # whichever tenant's run happened to use it. Cross-org promotion was
         # already removed for that reason; this removes the remaining
         # admin-created shared hints so the guarantee is structural.
         # scope='global' is a different axis (which queries a hint applies to,
         # WITHIN an org) and is retained.
         #
         # idx_nlfc_org_shared was (org_id, is_shared) and is the hint table's
         # ONLY org index; DROP COLUMN would take it away as a dependency. Every
         # hint read filters on org_id, so it is replaced rather than lost —
         # matching idx_anti_org / idx_anchors_org on the sibling tables.
         "CREATE INDEX IF NOT EXISTS idx_nlfc_org "
         "ON nl_feedback_corrections(org_id)",
         "DROP INDEX IF EXISTS idx_nlfc_org_shared",
         "ALTER TABLE nl_feedback_corrections DROP COLUMN IF EXISTS is_shared",
     )),
    (21, "Hint dedup indexes match the engine's dedup key (NULL-equal; global drops domain)",
     (
         # Two pre-existing gaps, closed together because they share one index set.
         #
         # 1. v18 indexed `domain`/`url` plainly, so Postgres treats two NULL
         #    domains as DIFFERENT keys while the engine's SELECT uses
         #    `IS NOT DISTINCT FROM`, which treats them as the SAME. One writer
         #    thread and one uvicorn worker hide the disagreement today; a
         #    second replica does not. COALESCE(x,'') aligns the index to the
         #    engine. (NULLS NOT DISTINCT would match it exactly, but it is
         #    PG15-only syntax and would fail into the silent-disable loop on
         #    an older server; the NULL-vs-'' conflation it avoids is
         #    unreachable — extract_domain yields None, never ''.)
         #
         # 2. The `keyword` triage category maps to scope='global', and
         #    _SCOPE_WHERE ignores `domain` for global hints — but `domain` was
         #    still in the dedup key, so the same correction typed on two sites
         #    became two org-wide hints with split evidence, both injected and
         #    neither ever reaching a lifecycle threshold. The global key is now
         #    (feedback_text, org_id) and gets its own partial index; the three
         #    predicates partition the table (scope is NOT NULL) so no row is
         #    keyed twice.
         #
         # ORDER IS LOAD-BEARING: merge, then CREATE under NEW names, then DROP
         # the old ones.
         #   * `CREATE UNIQUE INDEX IF NOT EXISTS` matches on relation NAME, not
         #     definition, so reusing uq_nlfc_dedup_general would succeed and
         #     change nothing — the v18 definition would survive silently.
         #   * Both ensure_schema call sites run autocommit
         #     (postgres_execution_memory.py, main.py), so a DROP that lands
         #     before a failing CREATE is durable: the table would have NO dedup
         #     uniqueness for the whole retry loop. Creating first means a failed
         #     CREATE leaves the old index standing, the version unrecorded, and
         #     the advisory-locked retry re-runs the merge and succeeds.
         #   * A failed migration does not crash the app. It raises inside
         #     PostgresExecutionMemory.__init__, which learning_registry catches,
         #     disabling the ENTIRE learning system behind one WARNING and
         #     retrying every 300s. Silent, so the merge must leave zero
         #     collisions and must be safe to run again.
         #
         # The merge DELETES absorbed rows rather than deactivating them: the
         # unique indexes carry no is_active predicate, so a deactivated
         # duplicate still aborts the CREATE. Deletion is safe — hint_audit has
         # no FK, and get_hints_by_id (IN list), attribution's `pre` dict,
         # trigger_events' JSON arrays and hint_workflow_trace all tolerate
         # dangling ids.
         #
         # ONE statement, not six. Every data-modifying CTE runs exactly once
         # and to completion in a single transaction, so the merge is
         # all-or-nothing under autocommit. Split across statements it would not
         # be: a counter UPDATE that commits before a failing DELETE leaves the
         # survivors holding the sum AND the absorbed rows in place, and the
         # 300s retry adds the sum again.
         """
         WITH ranked AS (
             SELECT id, evidence_count, applied_count, success_count,
                    failure_count, unused_count, last_seen, is_active,
                    conflict_flagged, conflict_flagged_at, conflict_flag_reason,
                    first_value(id) OVER (
                        PARTITION BY feedback_text, COALESCE(domain, ''), scope,
                                     COALESCE(org_id, '')
                        ORDER BY created_at, id) AS survivor_id
             FROM nl_feedback_corrections WHERE scope NOT IN ('url', 'global')
             UNION ALL
             SELECT id, evidence_count, applied_count, success_count,
                    failure_count, unused_count, last_seen, is_active,
                    conflict_flagged, conflict_flagged_at, conflict_flag_reason,
                    first_value(id) OVER (
                        PARTITION BY feedback_text, COALESCE(domain, ''),
                                     COALESCE(url, ''), scope,
                                     COALESCE(org_id, '')
                        ORDER BY created_at, id) AS survivor_id
             FROM nl_feedback_corrections WHERE scope = 'url'
             UNION ALL
             SELECT id, evidence_count, applied_count, success_count,
                    failure_count, unused_count, last_seen, is_active,
                    conflict_flagged, conflict_flagged_at, conflict_flag_reason,
                    first_value(id) OVER (
                        PARTITION BY feedback_text, COALESCE(org_id, '')
                        ORDER BY created_at, id) AS survivor_id
             FROM nl_feedback_corrections WHERE scope = 'global'
         ),
         -- The survivor is the oldest row of each group; everything else in it
         -- is absorbed. created_at is written by datetime.now(utc).isoformat()
         -- at every write site, so it sorts lexicographically; id breaks ties.
         absorbed AS (SELECT * FROM ranked WHERE id <> survivor_id),
         agg AS (
             SELECT survivor_id,
                    sum(evidence_count)   AS evidence_count,
                    sum(applied_count)    AS applied_count,
                    sum(success_count)    AS success_count,
                    sum(failure_count)    AS failure_count,
                    sum(unused_count)     AS unused_count,
                    max(last_seen)        AS last_seen,
                    max(is_active)        AS is_active,
                    max(conflict_flagged) AS conflict_flagged
             FROM absorbed GROUP BY survivor_id
         ),
         -- Newest flag metadata across the WHOLE group, survivor included, so
         -- a survivor that keeps its own flag keeps its own reason too.
         flag AS (
             SELECT DISTINCT ON (r.survivor_id)
                    r.survivor_id, r.conflict_flagged_at, r.conflict_flag_reason
             FROM ranked r JOIN agg a ON a.survivor_id = r.survivor_id
             WHERE r.conflict_flagged = 1
             ORDER BY r.survivor_id, r.conflict_flagged_at DESC NULLS LAST,
                      r.id DESC
         ),
         -- Independent-source rows follow the survivor. This moves T5's
         -- per-run claims (source_kind='workflow') too, deliberately: a run
         -- that already submitted this correction against an absorbed hint
         -- contributed once and must not be able to claim the survivor again.
         -- ON CONFLICT DO NOTHING collapses a source two rows of the group
         -- both carried.
         moved_evidence AS (
             INSERT INTO hint_evidence
                 (hint_id, source_kind, source_key, source_hash, bucket, created_at)
             SELECT b.survivor_id, e.source_kind, e.source_key, e.source_hash,
                    e.bucket, e.created_at
             FROM hint_evidence e JOIN absorbed b ON b.id = e.hint_id
             ON CONFLICT DO NOTHING
             RETURNING 1
         ),
         dropped_evidence AS (
             DELETE FROM hint_evidence
             WHERE hint_id IN (SELECT id FROM absorbed)
             RETURNING 1
         ),
         dropped_anchors AS (
             DELETE FROM learning_anchors
             WHERE kind = 'nl' AND record_id IN (SELECT id FROM absorbed)
             RETURNING 1
         ),
         -- Preserve-when-uncertain, one expression per column: served if ANY
         -- member was served, flagged if ANY member was flagged. A wrongly
         -- active survivor is re-disabled by the next real evidence through the
         -- live rules; a flagged survivor is recovered by resubmission (Gap 7).
         -- disabled_at is cleared when the merge reactivates, matching what the
         -- reactivate endpoints already do.
         merged AS (
             UPDATE nl_feedback_corrections s
             SET evidence_count = s.evidence_count + a.evidence_count,
                 applied_count  = s.applied_count  + a.applied_count,
                 success_count  = s.success_count  + a.success_count,
                 failure_count  = s.failure_count  + a.failure_count,
                 unused_count   = s.unused_count   + a.unused_count,
                 last_seen      = GREATEST(s.last_seen, a.last_seen),
                 is_active      = GREATEST(s.is_active, a.is_active),
                 disabled_at    = CASE WHEN GREATEST(s.is_active, a.is_active) = 1
                                       THEN NULL ELSE s.disabled_at END,
                 conflict_flagged =
                     GREATEST(s.conflict_flagged, a.conflict_flagged),
                 conflict_flagged_at =
                     CASE WHEN GREATEST(s.conflict_flagged, a.conflict_flagged) = 1
                          THEN f.conflict_flagged_at ELSE s.conflict_flagged_at END,
                 conflict_flag_reason =
                     CASE WHEN GREATEST(s.conflict_flagged, a.conflict_flagged) = 1
                          THEN f.conflict_flag_reason ELSE s.conflict_flag_reason END
             FROM agg a LEFT JOIN flag f ON f.survivor_id = a.survivor_id
             WHERE s.id = a.survivor_id
             RETURNING s.id AS survivor_id, s.evidence_count, s.applied_count,
                       s.success_count, s.failure_count, s.unused_count,
                       s.is_active, s.conflict_flagged
         ),
         -- One row per absorbed hint, on the SURVIVOR's timeline: that is where
         -- a reader looking at the jumped counters will be. hint_audit has no
         -- FK, so the row outlives the hint it describes. after_value reads
         -- `merged`'s RETURNING instead of recomputing the sums -- UPDATE
         -- RETURNING yields post-update values, and referencing another
         -- data-modifying CTE's output is what orders the two -- so the audit
         -- record cannot drift from the write it describes.
         audited AS (
             INSERT INTO hint_audit
                 (hint_id, action, actor, reason, before_value, after_value, created_at)
             SELECT b.survivor_id, 'merge', 'migration_v21',
                    'Duplicate hint absorbed by migration 21 (dedup key realigned)',
                    jsonb_build_object(
                        'id', b.id,
                        'evidence_count', b.evidence_count,
                        'applied_count', b.applied_count,
                        'success_count', b.success_count,
                        'failure_count', b.failure_count,
                        'unused_count', b.unused_count,
                        'is_active', b.is_active,
                        'conflict_flagged', b.conflict_flagged,
                        'last_seen', b.last_seen)::text,
                    jsonb_build_object(
                        'survivor_id', m.survivor_id,
                        'evidence_count', m.evidence_count,
                        'applied_count', m.applied_count,
                        'success_count', m.success_count,
                        'failure_count', m.failure_count,
                        'unused_count', m.unused_count,
                        'is_active', m.is_active,
                        'conflict_flagged', m.conflict_flagged)::text,
                    now()::text
             FROM absorbed b JOIN merged m ON m.survivor_id = b.survivor_id
             RETURNING 1
         )
         DELETE FROM nl_feedback_corrections WHERE id IN (SELECT id FROM absorbed)
         """,
         "CREATE UNIQUE INDEX IF NOT EXISTS uq_nlfc_dedup_general_v21 "
         "ON nl_feedback_corrections "
         "(feedback_text, COALESCE(domain, ''), scope, COALESCE(org_id, '')) "
         "WHERE scope NOT IN ('url', 'global')",
         "CREATE UNIQUE INDEX IF NOT EXISTS uq_nlfc_dedup_url_v21 "
         "ON nl_feedback_corrections "
         "(feedback_text, COALESCE(domain, ''), COALESCE(url, ''), scope, "
         " COALESCE(org_id, '')) "
         "WHERE scope = 'url'",
         "CREATE UNIQUE INDEX IF NOT EXISTS uq_nlfc_dedup_global_v21 "
         "ON nl_feedback_corrections (feedback_text, COALESCE(org_id, '')) "
         "WHERE scope = 'global'",
         "DROP INDEX IF EXISTS uq_nlfc_dedup_general",
         "DROP INDEX IF EXISTS uq_nlfc_dedup_url",
     )),
    (22, "hint_evidence lookup index (F3) + hint_review_pages.org_id (for T3)",
     (
         # F3: get_corrections_for_run (nl_feedback_engine.py) filters on
         # source_hash/source_kind/bucket with no hint_id, so uq_hint_evidence
         # (which leads with hint_id) cannot serve it — seq scan on every
         # FeedbackPanel mount. Measured at 1M rows: no index 23.7ms (Parallel
         # Seq Scan); a full (source_hash, source_kind, bucket) index gets it
         # to 0.434ms at 102MB; this partial index gets the same 0.5ms class
         # at 30MB by dropping source_kind into a WHERE predicate instead of
         # a leading column (only 'workflow' source_kind rows are ever looked
         # up this way). Insert-cost differences across all shapes measured
         # as noise, not a factor in the choice.
         "CREATE INDEX IF NOT EXISTS idx_hint_evidence_source "
         "ON hint_evidence (source_hash, bucket) WHERE source_kind = 'workflow'",
         # hint_review_pages predates org partitioning (Phase 1c). Nullable,
         # no backfill: existing pages have no correct org_id to backfill to.
         # Follows the v17 pattern: baseline DDL carries the column for fresh
         # installs, this ADD COLUMN carries it for existing databases.
         "ALTER TABLE hint_review_pages ADD COLUMN IF NOT EXISTS org_id TEXT",
     )),
)

if PG_MIGRATIONS and SCHEMA_VERSION != max(v for v, _, _ in PG_MIGRATIONS):
    raise RuntimeError(
        "pg_schema contract violation: SCHEMA_VERSION must equal the highest "
        "PG_MIGRATIONS entry"
    )

# Database-wide advisory lock serializing schema bootstrap/migration. Several
# components ensure the schema concurrently at startup (health check, learning
# store, …) and concurrent CREATE IF NOT EXISTS can fail with "tuple
# concurrently updated". Session-level so it works on autocommit connections.
_SCHEMA_LOCK_KEY = 0x6E6C7266  # 'nlrf'


def ensure_schema(conn) -> int:
    """Create the learning schema if absent and apply pending migrations.

    Idempotent. Serialized across processes/threads via an advisory lock.

    Args:
        conn: a psycopg connection (autocommit or transactional — we commit).

    Returns:
        SCHEMA_VERSION after ensuring the schema exists.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT pg_advisory_lock(%s)", (_SCHEMA_LOCK_KEY,))
        try:
            for ddl in PG_SCHEMA_DDL:
                cur.execute(ddl)
            # Record the consolidated baseline version once. This is the BASELINE
            # version, not SCHEMA_VERSION — see _BASELINE_VERSION. Recording the
            # latest version here would skip the migrations below on an existing DB.
            cur.execute(
                "INSERT INTO schema_version (version, description, applied_at) "
                "VALUES (%s, %s, now()::text) ON CONFLICT (version) DO NOTHING",
                (_BASELINE_VERSION, "Phase 4 consolidated Postgres schema (jsonb hint-id columns, slice 4.5)"),
            )
            # Apply any migrations this database has not recorded yet, in
            # version order (sorted, so authoring order in the tuple can't
            # accidentally reorder dependent migrations).
            cur.execute("SELECT version FROM schema_version")
            recorded = {row[0] for row in cur.fetchall()}
            for version, description, statements in sorted(PG_MIGRATIONS):
                if version in recorded:
                    continue
                for stmt in statements:
                    cur.execute(stmt)
                cur.execute(
                    "INSERT INTO schema_version (version, description, applied_at) "
                    "VALUES (%s, %s, now()::text) ON CONFLICT (version) DO NOTHING",
                    (version, description),
                )
                logger.info("[LEARNING] Applied schema migration v%d: %s", version, description)
        finally:
            cur.execute("SELECT pg_advisory_unlock(%s)", (_SCHEMA_LOCK_KEY,))
    conn.commit()
    logger.info("[LEARNING] Postgres learning schema ensured (v%d)", SCHEMA_VERSION)
    return SCHEMA_VERSION
