"""
PostgreSQL schema for the learning store (Phase 4 migration).

This is the consolidated, final-state DDL — the Postgres equivalent of all 14
SQLite migrations in schema_manager.py, collapsed into one CREATE-IF-NOT-EXISTS
schema (a fresh Postgres DB has no history to replay). Future schema changes add
numbered entries to PG_MIGRATIONS and bump SCHEMA_VERSION.

Porting decisions (minimise code churn — mirror SQLite shapes, not "ideal" PG):
- INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
- Timestamps stay TEXT (ISO-8601 strings), exactly like SQLite, so the engines'
  read/write code is unchanged. (Not native timestamptz — deliberate.)
- Boolean-ish columns stay INTEGER (is_active, test_passed, …) so engine code
  like `WHERE is_active = 1` ports verbatim.
- REAL -> DOUBLE PRECISION. JSON arrays stay TEXT (the dashboard JSON queries
  are ported separately to jsonb functions at read time).

Referenced by: postgres_execution_memory.py (Phase 4).
"""

import logging

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 16

# Each statement is executed once inside ensure_schema(). Ordered so referenced
# tables (nl_feedback_corrections, hint_review_sessions) exist before FKs.
PG_SCHEMA_DDL: tuple[str, ...] = (
    # --- schema_version bookkeeping ---
    """
    CREATE TABLE IF NOT EXISTS schema_version (
        version     INTEGER PRIMARY KEY,
        description TEXT,
        applied_at  TEXT NOT NULL
    )
    """,

    # --- execution_records (cols consolidated through v13) ---
    """
    CREATE TABLE IF NOT EXISTS execution_records (
        id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id           TEXT UNIQUE NOT NULL,
        timestamp             TEXT NOT NULL,
        user_query            TEXT NOT NULL,
        url                   TEXT,
        domain                TEXT,
        robot_code            TEXT,
        code_structure        TEXT,
        test_status           TEXT NOT NULL,
        execution_exit_code   INTEGER,
        execution_duration_ms INTEGER,
        failure_category      TEXT,
        failed_keyword        TEXT,
        error_message         TEXT,
        total_llm_calls       INTEGER DEFAULT 0,
        total_cost            DOUBLE PRECISION DEFAULT 0.0,
        user_feedback         TEXT,
        user_feedback_type    TEXT,
        working_code          TEXT,
        injected_hint_ids     JSONB,
        model_version         TEXT,
        hint_attribution_done INTEGER NOT NULL DEFAULT 1,
        CONSTRAINT chk_status CHECK (test_status IN ('passed', 'failed', 'error'))
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_exec_domain ON execution_records(domain)",
    "CREATE INDEX IF NOT EXISTS idx_exec_status ON execution_records(test_status)",
    "CREATE INDEX IF NOT EXISTS idx_exec_failure ON execution_records(failure_category)",
    "CREATE INDEX IF NOT EXISTS idx_exec_timestamp ON execution_records(timestamp)",
    "CREATE INDEX IF NOT EXISTS idx_exec_structure ON execution_records(code_structure)",
    # GIN index for jsonb hint-id membership (injected_hint_ids @> to_jsonb(id)) — Tier 1.
    "CREATE INDEX IF NOT EXISTS idx_exec_injected_gin ON execution_records USING GIN (injected_hint_ids)",

    # --- intent_patterns ---
    """
    CREATE TABLE IF NOT EXISTS intent_patterns (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        intent_name      TEXT UNIQUE NOT NULL,
        triggers_json    TEXT NOT NULL,
        requires_json    TEXT NOT NULL,
        source           TEXT NOT NULL,
        score            DOUBLE PRECISION DEFAULT 0.5,
        evidence_count   INTEGER DEFAULT 0,
        counter_evidence INTEGER DEFAULT 0,
        last_triggered   TEXT,
        last_updated     TEXT NOT NULL,
        created_at       TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_intent_score ON intent_patterns(score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_intent_source ON intent_patterns(source)",

    # --- structural_rules ---
    """
    CREATE TABLE IF NOT EXISTS structural_rules (
        id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        rule_name              TEXT UNIQUE NOT NULL,
        query_pattern          TEXT NOT NULL,
        required_structure     TEXT NOT NULL,
        required_keywords_json TEXT,
        code_template          TEXT,
        score                  DOUBLE PRECISION DEFAULT 0.5,
        evidence_count         INTEGER DEFAULT 0,
        counter_evidence       INTEGER DEFAULT 0,
        last_triggered         TEXT,
        last_updated           TEXT NOT NULL,
        created_at             TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_rules_score ON structural_rules(score DESC)",
    "CREATE INDEX IF NOT EXISTS idx_rules_score_evidence ON structural_rules(score DESC, evidence_count DESC)",

    # --- keyword_corrections ---
    """
    CREATE TABLE IF NOT EXISTS keyword_corrections (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        wrong_keyword   TEXT NOT NULL,
        correct_keyword TEXT,
        library         TEXT DEFAULT 'browser',
        error_pattern   TEXT,
        score           DOUBLE PRECISION DEFAULT 0.5,
        evidence_count  INTEGER DEFAULT 1,
        last_seen       TEXT NOT NULL,
        UNIQUE(wrong_keyword, library)
    )
    """,

    # --- anti_patterns ---
    """
    CREATE TABLE IF NOT EXISTS anti_patterns (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        failure_category    TEXT NOT NULL,
        query_pattern       TEXT,
        bad_code_snippet    TEXT,
        error_message       TEXT,
        correct_alternative TEXT,
        domain              TEXT,
        score               DOUBLE PRECISION DEFAULT 0.5,
        evidence_count      INTEGER DEFAULT 1,
        last_seen           TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_anti_category ON anti_patterns(failure_category)",
    "CREATE INDEX IF NOT EXISTS idx_anti_domain ON anti_patterns(domain)",
    "CREATE INDEX IF NOT EXISTS idx_anti_score_evidence ON anti_patterns(score DESC, evidence_count DESC)",

    # --- learning_stats ---
    """
    CREATE TABLE IF NOT EXISTS learning_stats (
        id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stat_date            TEXT NOT NULL,
        total_executions     INTEGER DEFAULT 0,
        total_passed         INTEGER DEFAULT 0,
        total_failed         INTEGER DEFAULT 0,
        rules_applied        INTEGER DEFAULT 0,
        rules_effective      INTEGER DEFAULT 0,
        avg_cost             DOUBLE PRECISION,
        avg_delegation_count DOUBLE PRECISION,
        feedback_received    INTEGER DEFAULT 0,
        UNIQUE(stat_date)
    )
    """,

    # --- learning_metrics (+ was_holdout v11) ---
    """
    CREATE TABLE IF NOT EXISTS learning_metrics (
        id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        workflow_id             TEXT NOT NULL,
        user_query              TEXT NOT NULL,
        is_first_attempt        INTEGER NOT NULL DEFAULT 1,
        is_retry_after_feedback INTEGER NOT NULL DEFAULT 0,
        attempt_number          INTEGER NOT NULL DEFAULT 1,
        hints_available         INTEGER NOT NULL DEFAULT 0,
        hints_injected          INTEGER NOT NULL DEFAULT 0,
        hint_sources            JSONB DEFAULT '[]'::jsonb,
        llm_calls               INTEGER NOT NULL DEFAULT 0,
        llm_cost                DOUBLE PRECISION NOT NULL DEFAULT 0.0,
        hint_tokens             INTEGER NOT NULL DEFAULT 0,
        test_passed             INTEGER NOT NULL,
        timestamp               TEXT NOT NULL,
        was_holdout             INTEGER NOT NULL DEFAULT 0
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_metrics_workflow ON learning_metrics(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_metrics_first_attempt ON learning_metrics(is_first_attempt)",
    "CREATE INDEX IF NOT EXISTS idx_metrics_hints ON learning_metrics(hints_injected)",

    # --- nl_feedback_corrections (cols consolidated through v13) ---
    """
    CREATE TABLE IF NOT EXISTS nl_feedback_corrections (
        id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        feedback_text             TEXT NOT NULL,
        category                  TEXT NOT NULL DEFAULT 'uncategorized',
        scope                     TEXT NOT NULL DEFAULT 'domain',
        domain                    TEXT,
        url                       TEXT,
        original_failure_category TEXT,
        evidence_count            INTEGER NOT NULL DEFAULT 1,
        applied_count             INTEGER NOT NULL DEFAULT 0,
        success_count             INTEGER NOT NULL DEFAULT 0,
        failure_count             INTEGER NOT NULL DEFAULT 0,
        is_active                 INTEGER NOT NULL DEFAULT 1,
        source_workflow_id        TEXT,
        created_at                TEXT NOT NULL,
        last_seen                 TEXT NOT NULL,
        conflict_flagged          INTEGER NOT NULL DEFAULT 0,
        conflict_flagged_at       TEXT,
        conflict_flag_reason      TEXT,
        created_via               TEXT NOT NULL DEFAULT 'workflow',
        disabled_at               TEXT,
        anchor_query              TEXT,
        unused_count              INTEGER NOT NULL DEFAULT 0,
        UNIQUE(feedback_text, domain, scope)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_nlfc_domain ON nl_feedback_corrections(domain)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_scope ON nl_feedback_corrections(scope)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_active ON nl_feedback_corrections(is_active)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_domain_scope ON nl_feedback_corrections(domain, scope)",
    "CREATE INDEX IF NOT EXISTS idx_nlfc_conflict ON nl_feedback_corrections(conflict_flagged)",
    # Partial index for the hot hint-retrieval filter (active, unflagged) — Tier 1.
    "CREATE INDEX IF NOT EXISTS idx_nlfc_active_unflagged ON nl_feedback_corrections(scope, domain) "
    "WHERE is_active = 1 AND conflict_flagged = 0",

    # --- trigger_events (cols consolidated through v13) ---
    """
    CREATE TABLE IF NOT EXISTS trigger_events (
        id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trigger_type              TEXT NOT NULL,
        workflow_id               TEXT,
        domain                    TEXT,
        url                       TEXT,
        feedback_text             TEXT,
        active_hint_ids           JSONB,
        flagged_hint_ids          JSONB,
        reason                    TEXT,
        llm_model                 TEXT,
        input_tokens              INTEGER,
        output_tokens             INTEGER,
        llm_latency_ms            INTEGER,
        status                    TEXT NOT NULL,
        error_message             TEXT,
        created_at                TEXT NOT NULL,
        actually_flagged_hint_ids JSONB,
        used_hint_ids             JSONB,
        unused_hint_ids           JSONB
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_trigger_events_created ON trigger_events(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_events_workflow ON trigger_events(workflow_id)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_events_type ON trigger_events(trigger_type)",
    # GIN indexes for jsonb hint-id membership (col @> to_jsonb(id)) — Tier 1.
    "CREATE INDEX IF NOT EXISTS idx_trigger_active_gin ON trigger_events USING GIN (active_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_flagged_gin ON trigger_events USING GIN (flagged_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_actually_flagged_gin ON trigger_events USING GIN (actually_flagged_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_used_gin ON trigger_events USING GIN (used_hint_ids)",
    "CREATE INDEX IF NOT EXISTS idx_trigger_unused_gin ON trigger_events USING GIN (unused_hint_ids)",

    # --- hint_audit (FK -> nl_feedback_corrections) ---
    """
    CREATE TABLE IF NOT EXISTS hint_audit (
        id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        hint_id      INTEGER NOT NULL,
        action       TEXT NOT NULL,
        actor        TEXT NOT NULL,
        reason       TEXT,
        before_value TEXT,
        after_value  TEXT,
        created_at   TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_hint_audit_hint ON hint_audit(hint_id)",
    "CREATE INDEX IF NOT EXISTS idx_hint_audit_created ON hint_audit(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_hint_audit_actor ON hint_audit(actor)",

    # --- hint_review_sessions ---
    """
    CREATE TABLE IF NOT EXISTS hint_review_sessions (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status         TEXT NOT NULL DEFAULT 'pending_llm',
        hint_count     INTEGER NOT NULL DEFAULT 0,
        llm_model      TEXT,
        llm_latency_ms INTEGER,
        warning        TEXT,
        error_message  TEXT,
        created_at     TEXT NOT NULL,
        completed_at   TEXT
    )
    """,

    # --- hint_review_recommendations ---
    """
    CREATE TABLE IF NOT EXISTS hint_review_recommendations (
        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id        INTEGER NOT NULL,
        hint_id           INTEGER NOT NULL,
        recommendation    TEXT NOT NULL,
        reason            TEXT NOT NULL,
        exoneration_count INTEGER NOT NULL DEFAULT 0,
        admin_decision    TEXT,
        admin_notes       TEXT,
        decided_at        TEXT,
        applied           INTEGER NOT NULL DEFAULT 0,
        created_at        TEXT NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_hrr_session ON hint_review_recommendations(session_id)",
    "CREATE INDEX IF NOT EXISTS idx_hrr_hint ON hint_review_recommendations(hint_id)",

    # --- hint_review_pages ---
    """
    CREATE TABLE IF NOT EXISTS hint_review_pages (
        id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id     INTEGER NOT NULL,
        scope_type     TEXT NOT NULL,
        scope_value    TEXT,
        status         TEXT NOT NULL,
        hint_count     INTEGER NOT NULL,
        llm_latency_ms INTEGER,
        error_message  TEXT,
        retry_count    INTEGER DEFAULT 0,
        created_at     TEXT NOT NULL,
        completed_at   TEXT
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_review_pages_session ON hint_review_pages(session_id)",

    # --- hint_workflow_trace (composite PK, no FK by design) ---
    """
    CREATE TABLE IF NOT EXISTS hint_workflow_trace (
        workflow_id        TEXT NOT NULL,
        hint_id            INTEGER NOT NULL,
        scope              TEXT,
        source             TEXT,
        priority           TEXT,
        similarity_score   DOUBLE PRECISION,
        available          INTEGER NOT NULL DEFAULT 0,
        injected           INTEGER NOT NULL DEFAULT 0,
        drop_reason        TEXT,
        attribution_bucket TEXT,
        attribution_reason TEXT,
        created_at         TEXT NOT NULL,
        PRIMARY KEY (workflow_id, hint_id)
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_hint_trace_created_at ON hint_workflow_trace(created_at)",

    # --- pgvector embeddings (Phase 4 slice 6; replaces ChromaDB) ---
    # SCHEMA public pins the extension so the vector TYPE resolves from any
    # search_path that includes public. Without it, the first bootstrap on a
    # fresh database (e.g. CI's service container) installs into the first
    # search_path schema — an isolated test schema — and every other schema's
    # DDL then fails with 'type "vector" does not exist'.
    # 384 dims = fastembed all-MiniLM-L6-v2 (see embedding.EMBED_MODEL).
    "CREATE EXTENSION IF NOT EXISTS vector SCHEMA public",
    # learning_anchors — the hint-retrieval similarity gate (filter_by_query_similarity).
    """
    CREATE TABLE IF NOT EXISTS learning_anchors (
        anchor_key   TEXT PRIMARY KEY,
        kind         TEXT NOT NULL,
        record_id    BIGINT NOT NULL,
        anchor_query TEXT NOT NULL,
        embedding    vector(384) NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_anchors_kind_record ON learning_anchors(kind, record_id)",
    "CREATE INDEX IF NOT EXISTS idx_anchors_embedding "
    "ON learning_anchors USING hnsw (embedding vector_cosine_ops)",
    # execution_embeddings — per-execution query embeddings (find_similar_executions).
    """
    CREATE TABLE IF NOT EXISTS execution_embeddings (
        workflow_id      TEXT PRIMARY KEY,
        user_query       TEXT,
        test_status      TEXT,
        failure_category TEXT,
        domain           TEXT,
        code_structure   TEXT,
        embedding        vector(384) NOT NULL
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_exec_emb_embedding "
    "ON execution_embeddings USING hnsw (embedding vector_cosine_ops)",

    # --- SQLite-compat SQL functions (so the engines' SQLite SQL runs as-is) ---
    # NOTE: json_each / json_valid were retired in slice 4.5 — the hint-id array
    # columns are now native jsonb and the KPI queries use jsonb operators
    # (col @> to_jsonb(id)) directly, so no text-JSON emulation is needed.
    # SQLite datetime('now', <modifiers...>) -> Postgres text "YYYY-MM-DD HH24:MI:SS".
    # The engines only use 'now'/'localtime' and day-interval modifiers
    # ("-30 days", "? || ' days'"); all base modifiers map to **UTC** and
    # interval modifiers are applied on top.
    # UTC, NOT localtimestamp: the Python writers in the same tables stamp
    # datetime.now(timezone.utc), and with run.sh the backend (host TZ) and
    # Postgres (UTC container) disagree on "local" — server-local here would
    # skew every cross-writer comparison and retention window by the TZ offset.
    # ('localtime' is accepted for source compatibility but still means UTC.)
    """
    CREATE OR REPLACE FUNCTION datetime(VARIADIC mods text[])
    RETURNS text LANGUAGE plpgsql AS $fn$
    DECLARE ts timestamp := (now() at time zone 'utc'); m text; i int;
    BEGIN
        IF mods IS NOT NULL THEN
            FOR i IN 1 .. COALESCE(array_length(mods, 1), 0) LOOP
                m := mods[i];
                IF m IS NULL OR m IN ('now', 'localtime', 'utc') THEN
                    CONTINUE;
                ELSIF m ~* '(day|hour|month|year|minute|second|week)' THEN
                    ts := ts + m::interval;
                END IF;
            END LOOP;
        END IF;
        RETURN to_char(ts, 'YYYY-MM-DD HH24:MI:SS');
    END $fn$
    """,
    # SQLite last_insert_rowid() -> Postgres lastval() (last IDENTITY/sequence
    # value in the session). Valid only right after an INSERT on the same conn,
    # which is exactly how the call sites use it.
    """
    CREATE OR REPLACE FUNCTION last_insert_rowid()
    RETURNS bigint LANGUAGE sql AS $fn$ SELECT lastval() $fn$
    """,
)


# ---------------------------------------------------------------------------
# Forward-only migrations for EXISTING databases.
#
# The consolidated DDL above always describes the CURRENT schema, but CREATE
# IF NOT EXISTS never alters a table that already exists — so a change to an
# existing table needs BOTH:
#   1. the change folded into PG_SCHEMA_DDL (fresh databases), AND
#   2. a numbered entry here (existing databases), AND
#   3. SCHEMA_VERSION bumped to the new number.
# Contract: every migration statement must be idempotent (ADD COLUMN IF NOT
# EXISTS, CREATE INDEX IF NOT EXISTS, …) — on a fresh database the baseline
# DDL already contains the change and the migration re-runs as a no-op.
# Each entry: (version, description, (statement, ...)).
# ---------------------------------------------------------------------------
PG_MIGRATIONS: tuple[tuple[int, str, tuple[str, ...]], ...] = (
    # Example:
    # (17, "track per-hint cost on execution_records",
    #  ("ALTER TABLE execution_records ADD COLUMN IF NOT EXISTS hint_cost DOUBLE PRECISION",)),
)

if PG_MIGRATIONS and SCHEMA_VERSION != max(v for v, _, _ in PG_MIGRATIONS):
    raise RuntimeError(
        "pg_schema contract violation: SCHEMA_VERSION must equal the highest "
        "PG_MIGRATIONS entry"
    )

# Database-wide advisory lock serializing schema bootstrap/migration. Several
# components ensure the schema concurrently at startup (health check, learning
# store, …) and concurrent CREATE IF NOT EXISTS can fail with "tuple
# concurrently updated". Session-level so it works on autocommit connections.
_SCHEMA_LOCK_KEY = 0x6E6C7266  # 'nlrf'


def ensure_schema(conn) -> int:
    """Create the learning schema if absent and apply pending migrations.

    Idempotent. Serialized across processes/threads via an advisory lock.

    Args:
        conn: a psycopg connection (autocommit or transactional — we commit).

    Returns:
        SCHEMA_VERSION after ensuring the schema exists.
    """
    with conn.cursor() as cur:
        cur.execute("SELECT pg_advisory_lock(%s)", (_SCHEMA_LOCK_KEY,))
        try:
            for ddl in PG_SCHEMA_DDL:
                cur.execute(ddl)
            # Record the consolidated baseline version once.
            cur.execute(
                "INSERT INTO schema_version (version, description, applied_at) "
                "VALUES (%s, %s, now()::text) ON CONFLICT (version) DO NOTHING",
                (SCHEMA_VERSION, "Phase 4 consolidated Postgres schema (jsonb hint-id columns, slice 4.5)"),
            )
            # Apply any migrations this database has not recorded yet, in
            # version order (sorted, so authoring order in the tuple can't
            # accidentally reorder dependent migrations).
            cur.execute("SELECT version FROM schema_version")
            recorded = {row[0] for row in cur.fetchall()}
            for version, description, statements in sorted(PG_MIGRATIONS):
                if version in recorded:
                    continue
                for stmt in statements:
                    cur.execute(stmt)
                cur.execute(
                    "INSERT INTO schema_version (version, description, applied_at) "
                    "VALUES (%s, %s, now()::text) ON CONFLICT (version) DO NOTHING",
                    (version, description),
                )
                logger.info("[LEARNING] Applied schema migration v%d: %s", version, description)
        finally:
            cur.execute("SELECT pg_advisory_unlock(%s)", (_SCHEMA_LOCK_KEY,))
    conn.commit()
    logger.info("[LEARNING] Postgres learning schema ensured (v%d)", SCHEMA_VERSION)
    return SCHEMA_VERSION
